config/routes.rb
Rails.application.routes.draw do
  
 
  get 'projects/new'
  get 'projects/index'
  get 'projects/show'
  get 'projects/edit'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, onry: [:index,:show,:create,:edit, :update, :destroy] do
    resource :nicetry, only: [:create,:destroy]
  end
  resources :jobs, onry: [:index,:create, :edit, :update, :destroy]
  resources :projects do
    resource :favorite
    resource :flow
    resource :cost
  end
  root 'homes#about'
  get 'homes/inquery'
  get 'jobs/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cost.rb
class Cost < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/flow.rb
class Flow < ApplicationRecord
belongs_to :project
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/nice_try.rb
class NiceTry < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
has_many :flows, dependent: :destroy

enum status: {"アイデア募集中":0, "アクション中":1, "未達成":2, "達成":3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController

  def create
    @flow = new(flow_params)

  end

  def flow_params
    params.require(:project_id,:name:process_time,:imrovement_flg)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def inquery
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @job = Job.new
    @jobs = Job.all
  end

  def create
    @job = Job.new(job_params)
    @job.save
    redirect_to jobs_path
  end

  def edit
    @job = Job.find(params[:id])
  end 

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    redirect_to jobs_path
  end
  
  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  private
  def job_params
  	params.require(:job).permit(:name, :amount)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
    @status = params[:status_selection]
  end

  def create
    @project = project.new(project_params)
    @project.save
    redirect_to project_path
    #flowレコードの作成
    @flow = @project.flow
  end

  def index
    @projects = Project.all
  end

  def show
  end

  def edit
  end

  private
  def project_params
    params.require(:project).permit(:name, :content, :stat_date, :finish_date, :status, :reducation_time, :total_amount, :total_amount, :reducation_amount, :number_of_month)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)  
      redirect_to user_path(current_user)
    else
      @user = current_user
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:family_name,:farst_name,:job_id, :admin_status, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>Homes#about</h1>
<p>Find me in app/views/homes/about.html.erb</p>

app/views/homes/inquery.html.erb
<h1>Homes#inquery</h1>
<p>Find me in app/views/homes/inquery.html.erb</p>

app/views/jobs/edit.html.erb
<h2 class="page-header text-center">登録情報編集</h2><br>
  <div class="row-center">
    <div class="col-md-12">
      <%= link_to "提案する", %>
    </div>
  </div>
  <div class="row center">
    <div class="col-md-12">
      <div class= "form-group">
        <%= form_with model: [@job], local: true do |f| %>
      </div>
      <div class= "form-group">
          <%= f.label :"職種:" %>
          <%= f.text_field :name %>
      </div>
      <div class= "form-group">
          <%= f.label :"金額:" %>
          <%= f.text_field :amount %>
      </div>
      <div class= 'text-center'>
        <%= f.submit '更新', class:"btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/jobs/index.html.erb
<h2>職種一覧</h2>
  <div class="row">
    <div class="col-md-12">
      <div class= "form-group"> 
        <%= form_with model:[@job] do |f| %>
      </div>
      <div class= "form-group">
        <%= f.label :"職種名" %>
        <%= f.text_field :name %>
      </div>  
      <div class= "form-group">
        <%= f.label :"金額" %>
        <%= f.text_field :amount %>
      </div>  
    </div>
    <%= f.submit :"職種の追加",  class:"btn btn-primary" %>
    <% end %>
  </div>
    <!-- 職種一覧 -->
  <div class="row">
    <div class="col-md-12">
      <table class="table">
        <tr>
        <th>No.</th>
        <th>名前</th>
        <th>金額</th>
        <th></th>
        <th></th>
        </tr>
        <% @jobs.each do |job| %>
          <tr>
            <td><%= job.id %></td>
            <td><%= job.name %></td>
            <td><%= job.amount  %> 円</td>
            <td>
              <%= link_to("編集",edit_job_path(job), {class: "btn btn-success"}) %>
              <%= link_to("削除", job_path(job), method: :delete, class: "btn btn-danger pull-right") %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h2 class="page-header text-center border-bottom">提案一覧</h2>
<div class="row">
  <div class="col-md-12">
    <%= link_to "提案する",new_project_path, {class: "btn btn-success"} %>
    <canvas id="myChart" width="900" height="400"></canvas>
<script>
var ctx = document.getElementById("myChart").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ["4月","5月","6月","7月","8月","9月","10月","11月","12月"],
        datasets: [{
            label: "削減総時間",
            data: [1,24,3,23,3,6,7,48,9,5,11,20],
            backgroundColor: 'rgba(255, 99, 132, 1.0)',
            borderColor: 'rgba(255, 50, 132, 1.0)',
            fill: false
        }]
    },
    options: {
        title:  {
          display: true,
          text: "タイトル"
        }
    }
});
</script>
  </div>
</div>
<div class="row">
  <% @projects.each do |project| %>
    <table class="table">
    <tr>
      <td><%= project.id %></td>
      <td><%= project.name %></td>
      <td><%= project.content %></td>
      
    </tr>
    </table>
  <% end %>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-6 text-center">
    <div class="form-group">
      <%= form_with(model:[@project], local: true) do |f| %>
    </div>
    <div class="form-group">
      <%= f.label :"プロジェクト名：" %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :"内容：" %>
      <%= f.text_area :content %>
    </div>
    <div class="form-group">
      <%= f.label :"開始日：" %>
      <%= raw sprintf(
        f.date_select(:"start_date",   
        use_month_numbers: true,
        start_year:        2020,
        end_year:          (Time.now.year + 20),
        default:           Date.new(2020, 1, 1),
        date_separator:    '%s'), # 年月日区切りをそれぞれ指定
            '年 ', '月 ') + '日' %>
    </div>
    <div class="form-group">
      <%= f.label :"終了日：" %>
      <%= raw sprintf(
      f.date_select(:"finish_date",   
      use_month_numbers: true,
      start_year:        2020,
      end_year:          (Time.now.year + 20),
      default:           Date.new(2020, 1, 1),
      date_separator:    '%s'), # 年月日区切りをそれぞれ指定
          '年 ', '月 ') + '日' %>
    </div>
    <div class="form-group"> 
      <%= f.label :"月回数" %>
      <%= f.text_field :number_of_month %>
    </div>
    <div class="form-group"> 
      <%= f.label :"ステータス：" %>
      <%= f.select :status, Project.statuses.keys.to_a %>
    </div>
    <%= f.submit '次へ', class:"btn btn-primary" %>
    <% end %>
  </div>
</div>
<!-- 改善時間の比較 -->
<div class="row">
  <%= form_with(model:[@project], local: true) do |f| %>
  <div class="col-md-6">
  <table>
    <tr>
     <td>
    <p>改善前</p>
      <div class="form-group">
        <%= f.label :"工程名：" %>
        <%= f.text_field :name %>
        <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
      </div>
      <div class="form-group">
        <%= f.label :"工程名：" %>
        <%= f.text_field :name %>
        <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
      </div>
      <div class="form-group">
        <%= f.label :"工程名：" %>
        <%= f.text_field :name %>
        <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
      </div>
      <div class="form-group">
        <%= f.label :"工程名：" %>
        <%= f.text_field :name %>
        <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
      </div>
      <div class="form-group">
        <%= f.label :"工程名：" %>
        <%= f.text_field :name %>
        <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
      </div>
      <div class="form-group">
        <%= f.label :"工程名：" %>
        <%= f.text_field :name %>
        <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
      </div>
    </td>   
  </div>
  <div class="col-md-6">

  <td>
    <p>改善後</p>
    <div class="form-group">
      <%= f.label :"工程名：" %>
      <%= f.text_field :name %>
      <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
    </div>
    <div class="form-group">
      <%= f.label :"工程名：" %>
      <%= f.text_field :name %>
      <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
    </div>
    <div class="form-group">
      <%= f.label :"工程名：" %>
      <%= f.text_field :name %>
      <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
    </div>
    <div class="form-group">
      <%= f.label :"工程名：" %>
      <%= f.text_field :name %>
      <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
    </div>
    <div class="form-group">
      <%= f.label :"工程名：" %>
      <%= f.text_field :name %>
      <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
    </div>
    <div class="form-group">
      <%= f.label :"工程名：" %>
      <%= f.text_field :name %>
      <%= f.label :"作業時間：" %>
        <%= f.time_select :reducation_time %>
    </div>
   </td>
  </div>

  </tr>
 </table> 
  <% end %>
</div>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>

app/views/users/edit.html.erb
<h2 class="page-header text-center">登録情報編集</h2><br>
  <div class="row center">
    <div class="col-md-12">
      <div class= "form-group">
        <%= form_with(model:[@user], local: true) do |f| %>
      </div>
      <div class= "form-group">
          <%= f.label :"名前:" %>
          <%= f.text_field :family_name %>
          <%= f.text_field :farst_name %>
      </div>
      <div class= "form-group">
          <%= f.label :"職種:" %>
          <%= f.text_field :job_id %>
      </div>
      <div class= 'text-center'>
        <%= f.submit '編集する', class:"btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>

app/views/users/index.html.erb
<div class= "row">
  <div class= "col-md-12">
    <% @users.each do |user| %>
      <table class= "table">
        <th><p>会員id</p></th>
        <th><p>会員名</p></th>
        <th><p>職種</p></th>
        <th><p>ナイストライ数</p></th>
        <th><p></p></th>
        <tr>
          <td> <%= user.id %> </td>
          <td> <%= link_to user.family_name + user.farst_name,user_path(user.id) %> 
          </td>
          <td><%= user.job_id %></td>
          <td> <p>"ナイストライ"　</p></td>
          <td> <%= link_to "編集", edit_user_path(user),class:"btn btn-primary"  %></td>
        </tr>
      </table>
    <% end %>
  </div>
</div>

</div>

app/views/users/show.html.erb
<h2 class="page-header text-center"><%= @user.family_name + @user.farst_name %>のページ</h2><br>

<div class="row">
  <div class="col-md-12">
    <div class="text-center">最近参加したプロジェクト</div>
  </div>
</div>