config/routes.rb
Rails.application.routes.draw do
  
 
  get 'projects/new'
  get 'projects/index'
  get 'projects/show'
  get 'projects/edit'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, onry: [:index,:show,:create,:edit, :update, :destroy] do
    resource :nicetry, only: [:create,:destroy]
  end
  resources :jobs, onry: [:index,:create, :edit, :update, :destroy]
  resources :projects do
    resource :favorite
    resource :flow
    resource :cost
  end
  root 'homes#about'
  get 'homes/inquery'
  get 'jobs/index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/cost.rb
class Cost < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/flow.rb
class Flow < ApplicationRecord
belongs_to :project
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/nice_try.rb
class NiceTry < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
has_many :flows, dependent: :destroy

enum status: {"アイデア募集中":0, "アクション中":1, "未達成":2, "達成":3}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/flows_controller.rb
class FlowsController < ApplicationController

  def create
    @flow = new(flow_params)

  end

  def flow_params
    params.require(:project_id,:name:process_time,:imrovement_flg)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end

  def inquery
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @job = Job.new
    @jobs = Job.all
  end

  def create
    @job = Job.new(job_params)
    @job.save
    redirect_to jobs_path
  end

  def edit
    @job = Job.find(params[:id])
  end 

  def update
    @job = Job.find(params[:id])
    @job.update(job_params)
    redirect_to jobs_path
  end
  
  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    redirect_to jobs_path
  end

  private
  def job_params
  	params.require(:job).permit(:name, :amount)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
    @project = Project.new
    @status = params[:status_selection]
  end

  def create
    @project = project.new(project_params)
    @project.save
    redirect_to project_path
    #flowレコードの作成
    @flow = @project.flow
  end

  def index
    @projects = Project.all
  end

  def show
  end

  def edit
  end

  private
  def project_params
    params.require(:project).permit(:name, :content, :stat_date, :finish_date, :status, :reducation_time, :total_amount, :total_amount, :reducation_amount, :number_of_month)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
     @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)  
      redirect_to user_path(current_user)
    else
      @user = current_user
      render :edit
    end
  end
  private
  def user_params
    params.require(:user).permit(:family_name,:farst_name,:job_id, :admin_status, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flows_helper.rb
module FlowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kaizen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="nav navbar-nav navbar-right navbar-inverse" style= "background-color: #192437;">
      <div class= 'ccontainer-fluid'>
        <div class= "row">
          <div class= 'col-md-5'>
            <nav class="nav navbar-nav navbar-left">
            </nav>
          </div>
          <div class= 'col-md-2'>
          </div>
          <div class= 'col-md-5'>
            <% if user_signed_in? %>
              <%= link_to("マイページ",user_path(current_user.id)) %>
              <%= link_to("会員一覧",users_path) %>
              <%= link_to("提案一覧",projects_path) %>
              <%= link_to(" ログアウト", destroy_user_session_path) %>
            <% else %>
               <%= link_to("about",root_path,{class: "glyphicon glyphicon-log-in"})%>
               <%= link_to("新規登録", new_user_registration_path)%>
               <%= link_to("ログイン", new_user_session_path)%>
            <% end %>
          </div>
        </div>
      </div>
    </nav>
    <div class= 'container'>
      <%= yield %>
    </div>
  </body>
</html>